apiVersion: apps/v1
kind: Deployment
metadata:
  name: peptide-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: validator
        image: validator-api:latest  # Use  local image
        imagePullPolicy: Never 
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: validator-service
  labels:
    app: validator
    release: monitoring
spec:
  selector:
    app: validator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

